name: Build & Deploy Front-end

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Inject your WP API URL
    env:
      NEXT_PUBLIC_WP_API_URL: ${{ secrets.NEXT_PUBLIC_WP_API_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build + static export
        run: |
          cd frontend
          npm run build

      - name: Deploy via SSH & rsync
          uses: appleboy/ssh-action@v0.1.6
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_SSH_PASSWORD }}
            port: ${{ secrets.SERVER_SSH_PORT }}
            debug: true
            script: |
              mkdir -p ~/public_html/app
              rsync -av --delete frontend/out/ ~/public_html/app/