name: Deploy Static Front-end via Rsync

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start ssh-agent & add key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync static export
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            frontend/out/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/public_html/app/