name: Build & Deploy Front-end via Rsync

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_WP_API_URL: ${{ secrets.NEXT_PUBLIC_WP_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          # Clean install of prod & dev deps (no optional at all)
          npm ci --legacy-peer-deps --omit=optional

      - name: Install LightningCSS binary for CI
        run: |
          cd frontend
          if [ "${{ runner.os }}" = "Linux" ]; then
            npm install lightningcss-linux-x64 --legacy-peer-deps
          else
            npm install lightningcss-darwin-arm64 --legacy-peer-deps
          fi

      - name: Build & export static site
        run: |
          cd frontend
          npm run build

      - name: Start ssh-agent & add key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync to server (auto-create folder)
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --rsync-path="mkdir -p ~/public_html/app && rsync" \
            frontend/out/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/public_html/app/
