name: Build & Deploy Front-end via Rsync

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_WP_API_URL: ${{ secrets.NEXT_PUBLIC_WP_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (legacy peer deps, skip optional)
        run: |
          cd frontend
          npm ci --legacy-peer-deps --no--optional

      - name: Start ssh-agent & add key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync to server (auto-create folder)
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --rsync-path="mkdir -p ~/public_html/app && rsync" \
            frontend/out/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/public_html/app/
